name: Publish a package

on:
    release:
        types: [released]
    workflow_dispatch:

jobs:
    publish-gh:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@${{github.repository_owner}}"
            - run: |
                  npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
                  npm install
              env:
                  NODE_AUTH_TOKEN: ${{ github.token }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  scope: "@${{github.repository_owner}}"
            - run: |
                  npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
                  npm install
              env:
                  NODE_AUTH_TOKEN: ${{github.token}}
            - run: |
                  npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
                  declare temp_npmrc="/home/runner/work/stackexchange-global-types/stackexchange-global-types/.npmrc"
                  truncate $temp_npmrc -s 0
                  echo "@${{github.repository_owner}}:registry=https://registry.npmjs.org" >> $temp_npmrc
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
